// src/pages/AICoachPage.jsx
import React, { useState, useMemo } from 'react';
import { AlertTriangle, TrendingUp, TrendingDown, Scissors, ChevronDown, ChevronUp, Info } from 'lucide-react';
import Card from '../components/common/Card';
import { PriorityBadge } from '../components/common/Badge';
import { getTransactions, getUser } from '../data/mockData';
import {
  getMonthlyExpenses, getCategoryBreakdown, detectAnomaly, getSpendingTrend,
} from '../utils/calculations';
import { formatCurrency, categoryLabels, categoryIcons } from '../utils/formatters';

function InsightCard({ icon, title, priority, children, defaultOpen = false }) {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <Card>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12, cursor: 'pointer' }} onClick={() => setOpen(o => !o)}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <div style={{ fontSize: 22, flexShrink: 0 }}>{icon}</div>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 2 }}>
              <span style={{ fontSize: 14, fontWeight: 700, color: '#0F1B2D' }}>{title}</span>
              <PriorityBadge priority={priority} />
            </div>
          </div>
        </div>
        <button style={{ background: 'none', border: 'none', color: '#52607A', cursor: 'pointer', flexShrink: 0, padding: 2 }}>
          {open ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
        </button>
      </div>
      {open && <div style={{ marginTop: 14, paddingTop: 14, borderTop: '1px solid #F5F7FA' }}>{children}</div>}
    </Card>
  );
}

function DataRow({ label, value, highlight }) {
  return (
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '6px 0', borderBottom: '1px solid #F5F7FA' }}>
      <span style={{ fontSize: 13, color: '#52607A' }}>{label}</span>
      <span style={{ fontSize: 13, fontWeight: 700, color: highlight || '#0F1B2D' }}>{value}</span>
    </div>
  );
}

export default function AICoachPage() {
  const transactions = getTransactions();
  const user = getUser();
  const income = user.monthlyIncome;

  const anomaly = useMemo(() => detectAnomaly(transactions), [transactions]);
  const catBreakdown = useMemo(() => getCategoryBreakdown(transactions, 2026, 10), [transactions]);
  const catMap = useMemo(() => {
    const m = {};
    catBreakdown.forEach(c => { m[c.category] = c.amount; });
    return m;
  }, [catBreakdown]);

  const augBreakdown = useMemo(() => getCategoryBreakdown(transactions, 2026, 8), [transactions]);
  const sepBreakdown = useMemo(() => getCategoryBreakdown(transactions, 2026, 9), [transactions]);
  const augMap = {}; augBreakdown.forEach(c => { augMap[c.category] = c.amount; });
  const sepMap = {}; sepBreakdown.forEach(c => { sepMap[c.category] = c.amount; });

  const octTotal = useMemo(() => getMonthlyExpenses(transactions, 2026, 10), [transactions]);
  const foodAvg = ((augMap.food || 0) + (sepMap.food || 0)) / 2;
  const shoppingAvg = ((augMap.shopping || 0) + (sepMap.shopping || 0)) / 2;
  const subAvg = ((augMap.subscriptions || 0) + (sepMap.subscriptions || 0)) / 2;

  const riskLevel = octTotal > income * 0.8 ? 'High' : octTotal > income * 0.6 ? 'Medium' : 'Low';
  const riskColor = riskLevel === 'High' ? '#B42318' : riskLevel === 'Medium' ? '#8F5200' : '#07704A';
  const predictedBalance = income - octTotal;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      {/* Disclaimer */}
      <div style={{ padding: '10px 14px', borderRadius: 8, background: '#F5F7FA', border: '1px solid #D9E0E9', display: 'flex', alignItems: 'center', gap: 8 }}>
        <Info size={15} style={{ color: '#52607A', flexShrink: 0 }} />
        <p style={{ fontSize: 12, color: '#52607A' }}>
          <strong>Note:</strong> These insights are generated by rule-based analysis of your demo data for Oct 2026, not by a live AI model.
        </p>
      </div>

      {/* Anomaly Spotlight */}
      {anomaly && (
        <div style={{
          padding: '16px 18px', borderRadius: 10,
          background: '#FFFBEB', border: '2px solid #FCD34D',
        }}>
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: 12 }}>
            <AlertTriangle size={22} style={{ color: '#8F5200', flexShrink: 0, marginTop: 2 }} />
            <div style={{ flex: 1 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                <span style={{ fontSize: 15, fontWeight: 800, color: '#8F5200' }}>⚠️ Unusual Expense Detected</span>
                <PriorityBadge priority="high" />
              </div>
              <p style={{ fontSize: 14, fontWeight: 700, color: '#0F1B2D', marginBottom: 2 }}>
                {anomaly.transaction.description}
              </p>
              <p style={{ fontSize: 13, color: '#52607A', marginBottom: 10 }}>
                {formatCurrency(Math.abs(anomaly.transaction.amount))} on {anomaly.transaction.date} —{' '}
                <strong style={{ color: '#8F5200' }}>{anomaly.deviation.toFixed(0)}% above</strong> your typical{' '}
                {categoryLabels[anomaly.transaction.category]} spend (avg {formatCurrency(anomaly.avgExcl)})
              </p>
              <div style={{ display: 'flex', gap: 12 }}>
                <div style={{ padding: '8px 14px', background: '#fff', borderRadius: 8, border: '1px solid #FCD34D' }}>
                  <div style={{ fontSize: 11, color: '#8F5200', marginBottom: 2 }}>This Transaction</div>
                  <div style={{ fontSize: 16, fontWeight: 800, color: '#B42318' }}>{formatCurrency(Math.abs(anomaly.transaction.amount))}</div>
                </div>
                <div style={{ padding: '8px 14px', background: '#fff', borderRadius: 8, border: '1px solid #D9E0E9' }}>
                  <div style={{ fontSize: 11, color: '#52607A', marginBottom: 2 }}>Category Average</div>
                  <div style={{ fontSize: 16, fontWeight: 800, color: '#0F1B2D' }}>{formatCurrency(anomaly.avgExcl)}</div>
                </div>
                <div style={{ padding: '8px 14px', background: '#fff', borderRadius: 8, border: '1px solid #D9E0E9' }}>
                  <div style={{ fontSize: 11, color: '#52607A', marginBottom: 2 }}>Deviation</div>
                  <div style={{ fontSize: 16, fontWeight: 800, color: '#B42318' }}>+{anomaly.deviation.toFixed(0)}%</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      <h3 style={{ fontSize: 15, fontWeight: 700, color: '#0F1B2D' }}>📈 Spending Observations</h3>

      {/* Food insight */}
      <InsightCard icon="🍽️" title="Food spending is lower than average" priority="low" defaultOpen={true}>
        <p style={{ fontSize: 13, color: '#52607A', marginBottom: 10, lineHeight: 1.6 }}>
          Your food spending in October is {formatCurrency(catMap.food || 0)}, which is below your 2-month average of {formatCurrency(foodAvg)}.
          Keep this trend going!
        </p>
        <DataRow label="August food spend" value={formatCurrency(augMap.food || 0)} />
        <DataRow label="September food spend" value={formatCurrency(sepMap.food || 0)} />
        <DataRow label="October food spend" value={formatCurrency(catMap.food || 0)} highlight="#07704A" />
        <DataRow label="2-month average" value={formatCurrency(foodAvg)} />
      </InsightCard>

      {/* Rent insight */}
      <InsightCard icon="🏠" title={`Rent is your largest expense at ${income > 0 ? (((catMap.rent || 0) / income) * 100).toFixed(1) : 0}% of income`} priority="medium">
        <p style={{ fontSize: 13, color: '#52607A', marginBottom: 10, lineHeight: 1.6 }}>
          Your monthly rent of {formatCurrency(catMap.rent || 15000)} accounts for a significant portion of your income.
          Financial advisors recommend keeping housing costs below 30% of income.
        </p>
        <DataRow label="Monthly rent" value={formatCurrency(catMap.rent || 15000)} highlight="#8F5200" />
        <DataRow label="% of monthly income" value={`${income > 0 ? (((catMap.rent || 15000) / income) * 100).toFixed(1) : 0}%`} />
        <DataRow label="30% income threshold" value={formatCurrency(income * 0.3)} />
      </InsightCard>

      {/* Shopping insight */}
      <InsightCard icon="🛍️" title="Shopping spiked in October" priority="high">
        <p style={{ fontSize: 13, color: '#52607A', marginBottom: 10, lineHeight: 1.6 }}>
          You spent {formatCurrency(catMap.shopping || 0)} on shopping in October — {shoppingAvg > 0 ? `${(((catMap.shopping || 0) - shoppingAvg) / shoppingAvg * 100).toFixed(0)}% above` : 'up from'} your 2-month average of {formatCurrency(shoppingAvg)}.
          Amazon, Flipkart, and Myntra are your top shopping platforms.
        </p>
        <DataRow label="August shopping" value={formatCurrency(augMap.shopping || 0)} />
        <DataRow label="September shopping" value={formatCurrency(sepMap.shopping || 0)} />
        <DataRow label="October shopping" value={formatCurrency(catMap.shopping || 0)} highlight="#B42318" />
        <DataRow label="2-month average" value={formatCurrency(shoppingAvg)} />
      </InsightCard>

      <h3 style={{ fontSize: 15, fontWeight: 700, color: '#0F1B2D', marginTop: 4 }}>✂️ Savings Suggestions</h3>

      {/* Food cut suggestion */}
      <InsightCard icon="🍜" title="Reduce food spending by 20%" priority="medium">
        <p style={{ fontSize: 13, color: '#52607A', marginBottom: 10, lineHeight: 1.6 }}>
          By reducing food orders by 20%, you could save approximately {formatCurrency((catMap.food || 0) * 0.2)} per month.
          Consider cooking at home a few more days a week.
        </p>
        <div style={{ padding: '10px 14px', background: '#E2F1F0', borderRadius: 8 }}>
          <div style={{ fontSize: 12, color: '#0B6E6E', fontWeight: 600 }}>Potential annual savings</div>
          <div style={{ fontSize: 22, fontWeight: 800, color: '#0B6E6E' }}>{formatCurrency((catMap.food || 0) * 0.2 * 12)}</div>
        </div>
      </InsightCard>

      {/* Streaming suggestion */}
      <InsightCard icon="📱" title="Optimise your subscriptions" priority="low">
        <p style={{ fontSize: 13, color: '#52607A', marginBottom: 10, lineHeight: 1.6 }}>
          You're currently paying {formatCurrency(catMap.subscriptions || 0)} across multiple streaming services this month (Netflix ₹649 + Spotify ₹119 + Amazon Prime ₹1,499).
          Cancelling one could free up significant funds.
        </p>
        <DataRow label="Current subscription spend" value={formatCurrency(catMap.subscriptions || 0)} highlight="#B42318" />
        <DataRow label="2-month average" value={formatCurrency(subAvg)} />
        <DataRow label="Potential monthly saving" value={formatCurrency(649)} highlight="#07704A" />
        <DataRow label="Annual saving (Netflix only)" value={formatCurrency(649 * 12)} highlight="#07704A" />
      </InsightCard>

      <h3 style={{ fontSize: 15, fontWeight: 700, color: '#0F1B2D', marginTop: 4 }}>🔮 Cash Flow Forecast</h3>

      {/* Forecast card */}
      <Card>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 14 }}>
          <TrendingUp size={18} style={{ color: '#0B6E6E' }} />
          <h3 style={{ fontSize: 14, fontWeight: 700, color: '#0F1B2D' }}>October 2026 Financial Health</h3>
          <span style={{ padding: '2px 10px', borderRadius: 20, fontSize: 11, fontWeight: 700, background: riskColor + '18', color: riskColor }}>
            {riskLevel} Risk
          </span>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 12, marginBottom: 14 }}>
          {[
            { label: 'Monthly Income', value: formatCurrency(income), color: '#07704A' },
            { label: 'Total Expenses', value: formatCurrency(octTotal), color: '#B42318' },
            { label: 'Remaining Balance', value: formatCurrency(Math.abs(predictedBalance)), color: predictedBalance >= 0 ? '#0B6E6E' : '#B42318' },
          ].map(item => (
            <div key={item.label} style={{ padding: '12px 14px', background: '#F5F7FA', borderRadius: 8, textAlign: 'center' }}>
              <div style={{ fontSize: 11, color: '#52607A', marginBottom: 4 }}>{item.label}</div>
              <div style={{ fontSize: 16, fontWeight: 800, color: item.color }}>{item.value}</div>
            </div>
          ))}
        </div>

        <p style={{ fontSize: 13, color: '#52607A', lineHeight: 1.7, padding: '10px 14px', background: predictedBalance >= 0 ? '#E2F1F0' : '#FEF2F2', borderRadius: 8 }}>
          {predictedBalance >= 0
            ? `✅ Your income of ${formatCurrency(income)} exceeds your expenses of ${formatCurrency(octTotal)} by ${formatCurrency(predictedBalance)} this month. Continue this pattern to build savings consistently.`
            : `⚠️ Your expenses of ${formatCurrency(octTotal)} exceed your income by ${formatCurrency(Math.abs(predictedBalance))}. This is primarily driven by the ₹28,500 laptop repair — a one-time anomaly. Without it, your balance would be positive.`
          }
        </p>
      </Card>
    </div>
  );
}
